services:
  gpu:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: "host"
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

  cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    volumes:
      - ${HOME}:/workspace
    working_dir: /workspace
    restart: always
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: "host"
    tty: true
    stdin_open: true
